### ISSUE TITLE
Graphical issues with Cyrix 486DX processors

### ISSUE THREAD

**Issue by viti95** [goshhhy/486quake#7] opened 2021-06-27 00:33 UTC
Maybe the FPU isn't 100% compatible with the Intel ones, and that causes the graphical issues.

![20210627_014958](https://user-images.githubusercontent.com/8323882/123529398-12c00000-d6f0-11eb-8ce5-78b1ef8235b4.jpg)
![20210627_014955](https://user-images.githubusercontent.com/8323882/123529405-1784b400-d6f0-11eb-8956-462dbaffdfbb.jpg)

**Comment by goshhhy** [comment] 2021-06-27 04:08
I have one of those, I'll test it and see what I can figure out.

**Comment by goshhhy** [comment] 2021-06-27 04:16
while I get it set up can you test with d_subdiv16 set to 0 and see if that still shows the issue?

**Comment by viti95** [comment] 2021-06-27 11:07
Changing d_subdiv16 to 0 made nothing. I've tested with other Cyrix CPUs and FPUs (TI 486DLC+ Cyrix Cx487DLC, Cyrix 486DX2-80, ST 486DX2-66) and all of them behave well except this processor, maybe the FPU is damaged in this one.

**Comment by goshhhy** [comment] 2021-07-18 00:10
closing this, as i can't reproduce the issue. if you find any more useful info or can reproduce with a different cpu, please reopen and add whatever info you have.

**Closed by goshhhy** 2021-07-18 00:10 UTC
Labels: bug
